"""empty message

Revision ID: eca91817ef67
Revises: 
Create Date: 2019-09-25 13:42:39.355975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca91817ef67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('finish_datetime', sa.DateTime(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('payment_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('norifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('notification_url', sa.String(), nullable=False),
    sa.Column('user_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('norifications')
    op.drop_table('payments')
    # ### end Alembic commands ###
